# Override the domain thats is used in the blobs "url" field
# By default it uses the domain the incoming HTTP request was made on
publicDomain: ""

databasePath: data/sqlite.db

dashboard:
  # enable or disable the admin dashboard
  enabled: true
  # admin username
  username: admin
  # if password is left blank it will be generated each time the app starts
  # password: ""

discovery:
  # find files by querying nostr relays
  nostr:
    enabled: true
    relays:
      - wss://nostrue.com
      - wss://relay.damus.io
      - wss://nostr.wine
      - wss://nos.lol
      - wss://nostr-pub.wellorder.net
  # find files by asking upstream CDNs
  # NOTE: do not set this to your own server, it will create an infinite loop
  upstream:
    enabled: true
    domains:
      - https://cdn.satellite.earth

storage:
  # local or s3
  backend: local

  # Imminently removes a blob when there are no owners
  removeWhenNoOwners: false

  # local storage
  local:
    dir: ./data/blobs

  # see minio docs for options:
  # https://min.io/docs/minio/linux/developers/javascript/API.html#new-minio-client-endpoint-port-usessl-accesskey-secretkey-region-transport-sessiontoken-partsize
  # s3:
  #   endpoint: https://s3.endpoint.com
  #   port: 443
  #   bucket: blossom
  #   accessKey: xxxxxxxx
  #   secretKey: xxxxxxxxx
  #   useSSL: true
  #   region: us-east-1
  #   If this is set the server will redirect clients when loading blobs
  #   publicURL: https://s3.region.example.com/

  # rules are checked in descending order. if a blob matches a rule it is kept
  # "type" (required) the type of the blob, "*" can be used to match any type
  # "expiration" (required) time passed since last accessed
  # "pubkeys" (optional) a list of owners
  # any blobs not matching the rules will be removed
  rules:
    # mime type of blob
    - type: text/*
      # time since last accessed
      expiration: 1 month
    - type: "image/*"
      expiration: 1 week
    - type: "video/*"
      expiration: 5 days
    - type: "model/*"
      expiration: 1 week
    - type: "*"
      expiration: 2 days

upload:
  # enable / disable uploads
  enabled: true
  # require auth to upload
  requireAuth: true
  # only check rules that include "pubkeys"
  requirePubkeyInRule: false

list:
  requireAuth: false
  allowListOthers: true

tor:
  enabled: false
  proxy: ""
